Added documentation with example usage
Valensas/simply-quartz pull request #6
Opened 2024-05-03 10:12 UTC by ofarukdogancay

Added documentation with example usage for quick start

@moray95 @cantaylancapraz

2024-05-03 13:13 UTC, can-arikan requested changes

2024-05-03 13:13 UTC, can-arikan commented on README.md
> +      org.quartz.jobStore.tablePrefix: qrtz_
we may change it to `<SERVICE_NAME>_qrtz_` hence it doesn't appear enough which may cause confusion if users try to create multiple micro-services in the same database

2024-05-03 13:13 UTC, can-arikan commented on README.md
> +  packagesToScan: com.example
do we still need this

2024-05-03 13:13 UTC, can-arikan commented on README.md
> +name: "quartz_scheduled_job"\
we may remove back slashes

2024-05-03 13:19 UTC, ofarukdogancay commented on README.md
> +  packagesToScan: com.example
Yes, in large projects it shouldn't scan all packages

2024-05-03 13:23 UTC, ofarukdogancay commented on README.md
> +name: "quartz_scheduled_job"\
New line character olarak geçiyor

2024-05-07 06:46 UTC, ofarukdogancay commented on README.md
> +      org.quartz.jobStore.tablePrefix: qrtz_
The default of quartz is qrtz_ , the property is shown for capability.

2024-05-07 07:34 UTC, moray95 commented on README.md
> +Simply Quartz
Burayı # başlık yapalım

2024-05-07 07:34 UTC, moray95 commented on README.md
> +Note: `@DisallowConcurrentExecution` belongs to quartz library, and `@QuartzSchedule` belongs to simply quartz library.
quartz -> Quartz
simply quartz -> SimplyQuartz

2024-05-07 08:24 UTC, merged